# Generated by Django 2.2.7 on 2019-11-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Itineraries',
            fields=[
                ('it_id', models.IntegerField(primary_key=True, serialize=False)),
                ('no_days', models.IntegerField(default=0)),
                ('total_kms', models.IntegerField(default=0)),
                ('it_desc', models.CharField(default='', max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'iti',
            },
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('dest_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dest_name', models.CharField(default='', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'dest',
            },
        ),
        migrations.CreateModel(
            name='basic_dest_ids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hello.Destinations', verbose_name='iti')),
                ('it_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='hello.Basic_Itineraries', verbose_name='dest')),
            ],
        ),
    ]
