# Generated by Django 2.2.7 on 2019-11-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_itineraries',
            old_name='no_days',
            new_name='no_das',
        ),
        migrations.RemoveField(
            model_name='basic_itineraries',
            name='total_kms',
        ),
    ]
