# Generated by Django 2.2.7 on 2019-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20191109_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_dest_ids',
            name='id',
        ),
        migrations.AddField(
            model_name='basic_dest_ids',
            name='b_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
