# Generated by Django 2.2.5 on 2019-11-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20191109_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_itineraries',
            name='it_desc',
            field=models.FileField(default='', max_length=10000, upload_to=''),
        ),
    ]
