# Generated by Django 2.2.5 on 2019-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20191119_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_itineraries',
            name='it_desc',
            field=models.CharField(max_length=256),
        ),
    ]
